engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - php
        - javascript
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "codesize,controversial,design,unusedcode"
  phpcodesniffer:
    enabled: true

ratings:
  paths:
    - src/**
    - "**.php"

exclude_paths:
  - vendor/**/*
  - .git/**/*
  - composer.*
